### ISSUE TITLE
Mapping to the raw file name.

### ISSUE THREAD

**Issue by WeiQijie** [BenediktAlkin/vtab1k-pytorch#1]
Hi,
I appreciate your great work. I'm looking for the image IDs of VTAB-1k dataset (because I have some problems with downloding them from the official tensorflow_dataset) and downloaded it from the link you provide in the repo. I found that all the images have been renamed. Could you please provide the mapppings of the raw image names and the image names you use. Thanks again.

**Comment by BenediktAlkin** [comment]
Hi, as described in the [readme](https://github.com/BenediktAlkin/vtab1k-pytorch/blob/main/SETUP_DATA.md), we use a fully preprocessed version that you can download from gdrive. So you dont need any mappings to setup the dataset.
